### ISSUE TITLE
Search no longer works after creating a Person

### ISSUE THREAD

**Issue by rogerstewart** [MisterJames/BootstrappingMvc-Code#1]
While following along in the book I found the following issue that can be reproduced with the repo.
- Load `/Person/Index` and verify `Search` functionality works.
- Navigate to `/Person/Create` and create a new `Person`. 
- Clicking `Create` adds the person to the database and redirects to `/Person/Index`.
- Attempt to use `Search` again and it does nothing.
  - Firebug shows a response of 404 with the following exception contained within:
    
    [HttpException]: The controller for path &#39;/SearchPeople&#39; was not found or does not implement IController.
    at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
    at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
    at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
    at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
    at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
    at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
    at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by MisterJames** [comment]
Hey @rogerstewart, sorry for the delay here. I'll try to address this ASAP.

**Comment by joeruder** [comment]
Hello;
I am having the same issue, but it seems to not be directing back to /Person/Index but just /Person.
If I manually go to /Person/Index it works.
